POST http://localhost:3000/api/llm/getToolSuggestion
Content-Type: application/json

{
    "query": "Which tool of what dimensions would you pick to mill 2 faces of 10 in2, dimensions of 4 in by 1.5 in, a perimeter of 14 in, a stock thickness of 1.5 in, and a depth per cut of 0.2 in? In your response make sure to include the diameter, flute length, and overall length, while returning tool diamentions, only use decimal places instead of fractions. Make sure tool diameter is smaller than smallest internal radius.",
    "output": [{
        "key": "TlDiameterBuilder",
        "type": "number",
        "description": "What is the value of the diameter of the suggested tool in the same unit as the feature?"
    }, {
        "key": "TlFluteLnBuilder",
        "type": "number",
        "description": "What is the value of the flute length of the suggested tool in the same unit as the feature?"
    }, {
        "key": "TlHeightBuilder",
        "type": "number",
        "description": "What is the value of the overall length of the suggested tool in the same unit as the feature?"
    }, {
        "key": "toolType",
        "type": "string",
        "description": "What is the type of the suggested tool? Can either be \"EndMillTool\", \"ChamferMillTool\", \"FaceMillTool\", or \"DrillTool\"."
    }]
}

###
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 115
ETag: W/"73-6d71y8JP/fPKOgf0eGtzpTPz29E"
Date: Tue, 05 Nov 2024 23:56:05 GMT
Connection: close

{
  "suggestedTool": {
    "TlDiameterBuilder": 0.5,
    "TlFluteLnBuilder": 1.2,
    "TlHeightBuilder": 6.25,
    "toolType": "FaceMillTool"
  }
}

###


POST http://localhost:3000/api/llm/getToolSuggestion
Content-Type: application/json

{
    "query": "Which tool of what dimensions would you pick to mill a contour of 2 walls, with a depth of 1 in, dimensions of 4 in by 1.5 in, and a smallest internal radius of 0.2 in? In your response make sure to include the diameter, flute length, and overall length, while returning tool diamentions, only use decimal places instead of fractions. Make sure tool diameter is smaller than smallest internal radius.",
    "output": [{
        "key": "TlDiameterBuilder",
        "type": "number",
        "description": "What is the value of the diameter of the suggested tool in the same unit as the feature?"
    }, {
        "key": "TlFluteLnBuilder",
        "type": "number",
        "description": "What is the value of the flute length of the suggested tool in the same unit as the feature?"
    }, {
        "key": "TlHeightBuilder",
        "type": "number",
        "description": "What is the value of the overall length of the suggested tool in the same unit as the feature?"
    }, {
        "key": "toolType",
        "type": "string",
        "description": "What is the type of the suggested tool? Can either be \"EndMillTool\", \"ChamferMillTool\", \"FaceMillTool\", or \"DrillTool\"."
    }]
}

### 
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 112
ETag: W/"70-BWpMxhP15sovja3nyLVNW9DTIs8"
Date: Tue, 05 Nov 2024 23:43:31 GMT
Connection: close

{
  "suggestedTool": {
    "TlDiameterBuilder": 4,
    "TlFluteLnBuilder": 0.125,
    "TlHeightBuilder": 1,
    "toolType": "FaceMillTool"
  }
}

###